### ISSUE TITLE
no styles

### ISSUE THREAD

**Issue by luisrudge** [Kindling/react-tinymce-mention#10]
It's returning the suggestions, but they're not working as the gif from the readme file. Is that the expected behavior?

![image](https://cloud.githubusercontent.com/assets/941075/20637673/fabe64bc-b375-11e6-80c4-82cbe4773a30.png)

**Comment by deltamualpha** [comment]
Correct, we don't add any styling to the mention, just add a class to them so you can style them however you like.

**Comment by luisrudge** [comment]
Any chance we can get some nice default styles? 💄

**Comment by deltamualpha** [comment]
Low on the priority list, to be honest. The ones in the demo gifs are just the default `a` styling -- your CSS must be overriding the browser default.
