### ISSUE TITLE
Components of this library must extend React.Component

### ISSUE THREAD

**Issue by RaitoBezarius** [Kindling/react-tinymce-mention#3]
It seems like that the `Mention` component which is exported does not inherit from `React.Component`, and neither is a React old-style class.

Is there any reason for this? Same goes for `SuggestionRenderer` and `DefaultList`.

Furthermore, in React 0.14, you don't need to wrap `<Provider>` child into a function.

**Comment by TuningGuide** [comment]
I really would like to use this Component but I'm unable to use it because React (15.3.x) complains about "Uncaught TypeError: Cannot call a class as a function". Could you fix this or tell me how to build the source myself?

**Comment by damassi** [comment]
@TuningGuide - Hi, i'm pretty far removed from this work at this point but feel free to fork and submit a PR and I'll merge. See https://github.com/Kindling/react-tinymce-mention#development for development instructions.

**Comment by damassi** [comment]
Fixed in https://github.com/Kindling/react-tinymce-mention/pull/4
