### ISSUE TITLE
Multi editor setup

### ISSUE THREAD

**Issue by TuningGuide** [Kindling/react-tinymce-mention#6]
Hi, do you know which parts I have to adapt in order to get the component working with multiple editors?

**Comment by damassi** [comment]
Can you explain a bit more?

**Comment by TuningGuide** [comment]
Sry, I'll try. I'm trying build a text editor where every chapter has its own tinymce editor. But I can only add mentions to the last tinymce instance.

The editor variable in plugin.js is not set to the active editor. Furthermore the loadMentions uses setTimeout and then on calling the function within setTimeout the editor is already set to another editor.

**Comment by damassi** [comment]
Woe is TinyMCE -- there was a lot of little hacks that had to be introduced in order to get everything working across different browsers. 

Again, I'm no longer on this project so I can't help you with this request, but the codebase is simple enough -- if you'd like to submit a PR i'll review and merge.

**Comment by TuningGuide** [comment]
I unterstand. I'll prepare something. But maybe you have an idea for my current problem:
the resolve function of the new Promise in initializePlugin only resolves the last promise. As if the resolve function would be overwritten. The resolve function is called as often as I have editor but all except the last promise are always in pending state

**Comment by TuningGuide** [comment]
Ahh, I always used the component wrong. I thought that for each editor I have to use a mention component. But you wrote it in a way that you only use one component for all editors.

**Comment by damassi** [comment]
Ok great :)
